name: Compile Agda and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  compile-agda:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    name: Compile Agda
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        cubical-ref: ["v0.8"]
        agda-ver: ["2.8.0"]

    steps:

    - name: Download Agda binary
      run: |
        set -e
        mkdir -p ~/.local/bin
        wget -qO- "https://github.com/agda/agda/releases/download/v${{ matrix.agda-ver }}/Agda-v${{ matrix.agda-ver }}-linux.tar.xz" | tar -xJ -C ~/.local/bin

    - name: Checkout cubical library
      uses: actions/checkout@v4.2.2
      with:
        repository: agda/cubical
        path: cubical
        ref: ${{ matrix.cubical-ref }}

    - name: Put cubical library in Agda library list
      run: |
        mkdir -p ~/.agda/
        touch ~/.agda/libraries
        echo "$GITHUB_WORKSPACE/cubical/cubical.agda-lib" > ~/.agda/libraries

    - name: Checkout main
      uses: actions/checkout@v4.2.2
      with:
        path: main

    - name: Restore cached dependencies
      uses: actions/cache/restore@v4.2.2
      id: cache
      with:
        path: |
          cubical/_build
          main/_build
          /home/runner/.local/share/agda/${{ matrix.agda-ver }}
        key: ${{ runner.os }}-v${{ matrix.agda-ver }}-${{ matrix.cubical.ref }}-${{ hashFiles('main/**') }}
        restore-keys: |
          ${{ runner.os }}-v${{ matrix.agda-ver }}-${{ matrix.cubical.ref }}-


    - name: Compile agda library
      run: |
        set -e
        cd main
        ./scripts/render.sh

    - name: Save cached dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4.2.2
      with:
        path: |
          cubical/_build
          main/_build
          /home/runner/.local/share/agda/${{ matrix.agda-ver }}
        key: ${{ runner.os }}-v${{ matrix.agda-ver }}-${{ matrix.cubical.ref }}-${{ hashFiles('main/**') }}

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'main/docs'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

